### ISSUE TITLE
How to visualize with obb

### ISSUE THREAD

**Issue by kotomiDu** [pboechat/pyobb#3]
Hi, I am new learner of 3d geometry. Your tool helps me a a lot to get oriented bounding box. But I don't know how to visualize it like what to show in the README.md. Could you give me some hints or url sources to guide me how to visualize it?

**Comment by pboechat** [comment]
Have you seen [pyobb/bin/pyobb_demos/3d_demo.py](https://github.com/pboechat/pyobb/blob/master/bin/pyobb_demos/3d_demo.py)?

**Comment by kotomiDu** [comment]
Thank you for your reminder.


发自我的iPhone

------------------ Original ------------------
