### ISSUE TITLE
Local frame of reference or global frame of reference

### ISSUE THREAD

**Issue by UrYuWang** [pboechat/pyobb#4]
For all these following:
centroid: the OBB center
min: the OBB point with the smallest XYZ components
max: the OBB point with the largest XYZ components
points: the 8 points of the OBB
extents: the extents of the OBB in the XYZ-axis
Are they based on the local frame of reference, or the global frame of reference?
I am kinda confused.
And should I use rotation.T as the base vector of OBB, and take the centroid as the origin of the local frame of reference?

**Comment by pboechat** [comment]
> Are they based on the local frame of reference, or the global frame of reference?

*min* and *max* are coordinates in the local system (aka local frame), whilst *centroid*, *extents* and *points* are in the world coordinate system (aka global frame).

> And should I use rotation.T as the base vector of OBB, and take the centroid as the origin of the local frame of reference?

Yes for both. *rotation* it is the _basis_ of the local coordinate system and *centroid* is the origin of the local coordinate system.
